# Generated by Django 4.2 on 2023-09-18 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rapport',
            old_name='statistique_id',
            new_name='rapport_id',
        ),
    ]
